//this file is generated by refreshResIndex.py,DON'T edit it by yourself!!!!

var res = {
	CloseNormal_png : "res/CloseNormal.png",
	CloseSelected_png : "res/CloseSelected.png",
	HelloWorld_png : "res/HelloWorld.png"
};


 var g_resources = [
	res.CloseNormal_png,
	res.CloseSelected_png,
	res.HelloWorld_png
];
