//this file is generated by ../RefreshResIndex.py,DONT edit it by yourself!!!!


var s_bg_png = "res/bg.png";
var s_flappy_packer_plist = "res/flappy_packer.plist";
var s_flappy_packer_png = "res/flappy_packer.png";
var s_ground_png = "res/ground.png";
var s_icon_wechat_png = "res/icon_wechat.png";
var s_number_png = "res/number.png";


 var g_resources = [ 
  s_bg_png,
  s_flappy_packer_plist,
  s_flappy_packer_png,
  s_ground_png,
  s_icon_wechat_png,
  s_number_png
];
